version: "3.8"

services:
  mysql:
    image: mysql:8.0.27
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: persistenciadb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql-dados:/var/lib/mysql  # Volume para persistência de dados
    networks:
      - minha-rede
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: mysql-container
      DATABASE_PORT: 3306
      DATABASE_DB: persistenciadb
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin  # Configuração de senha do banco
    networks:
      - minha-rede
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - minha-rede
    depends_on:
      - backend

volumes:
  mysql-dados:  # Volume persistente para o MySQL

networks:
  minha-rede:

